//
//  PlayWorldTests.generated.swift
//  PlayWorld
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

@testable import Mockingbird
@testable import PlayWorld
import Foundation
import Mockable
import Swift
import SwiftData
import SwiftUI

// No mocks used in 'PlayWorldTests'. Mockingbird is configured to only generate mocks for types
// that are explicitly initialized in your tests with `mock(SomeType.self)`. For more information,
// see 'Thunk Pruning' in the README.
